### ISSUE TITLE
Update a course based on a package version (or revert to old version)

### ISSUE THREAD

**Issue by oharac** [nceas-learning-hub/coreR#5]
To update a course to a different version of the lessons repo, we will need to:

* [x] nceas-learning-hub/coreR#6
    * This might be a date, a commit hash, a tag, a release - something in Github record
    * Choose a canonical way to reference these
* [x] nceas-learning-hub/coreR#7
    * Remember the original version to reinstall? or do a temp install elsewhere then delete it?
* [x] nceas-learning-hub/coreR#8
    * Based on matching filenames - if user has renamed a file, this will protect it; if the old file name doesn't match an updated filename, this will also not be updated
    * warn user with a list of files to be updated and files NOT to be updated
    * maybe with a "are you sure?" message
* [x] nceas-learning-hub/coreR#9
    * Copy and overwrite the lessons 
    * update the lesson versions in the quarto.yml?

**Comment by oharac** [comment]
done! works for now
